from models.patch_attention_unet_mf import PatchAttentionUNETMiddleFrame, Config as PatchAttentionUNETConfig
from models.patch_attention_unet_mf_v2 import PatchAttentionUNETMiddleFrame_v2, Config as PatchAttentionUNET_v2Config
from models.patch_attention_unet_li import PatchAttentionUNETLinearInterpolation, Config as PatchAttentionUNETLinearInterpolationConfig